### PR TITLE
 Enh1199596546867587: actionscript enh

### PR DESCRIPTION
**Pull request by alpenfritz**
## Issue

- https://app.asana.com/0/1198845117032545/1199596546867587:
  - Pre ActionScript  to check input errors  
  - Save logs of last execution
  - Download/Upload scripts as JS file

## Related Services

- linkermodels
- amagi
- apicore
- importer
- linker-api
- web-ui
- actionscript
- hexabase-cli

## Implementation

- add 2 new commands:
  - `hx actions:scripts:download ACTION_ID` (alias: `hx scripts:download ACTION_ID`)
  - `hx actions:scripts:upload ACTION_ID FILE` (alias: `hx scripts:upload ACTION_ID FILE`)

## Future work

-none

## Screenshots

image

image

image

### CODE REVIEW

**Review by iwask — CHANGES_REQUESTED** [review]
@alpenfritz Everything almost works well! and cool feature.  
but I found a small problem. 

when i use upload command, then Error Stop Flag seems reset and set to unchecked. please check. 

I used the command like this 
```
$ hx scripts:upload 6037e62728dc5c7bec5ee844 pre-6037e62728dc5c7bec5ee844.js -t pre
You are about to upload the script file to:
  action_id: 6037e62728dc5c7bec5ee844
  script_type: pre
  context: local
? Do you want to proceed? (y/y) » false
√ Do you want to proceed? (y/N) · true

uploading pre-script from file pre-6037e62728dc5c7bec5ee844.js... done
```

2021-02-26_03h30_21

**Comment by alpenfritz** [comment]
ok, i will check!

**Comment by alpenfritz** [comment]
@iwask i fixed the issue in the backend. Please test again.

**Review by iwask — APPROVED** [review]
OK.  I could check the flag problem is fixed!  Thank you.

**Pull request merged**
