### PR TITLE
Nguyen download setting

### PR DESCRIPTION
**Pull request by Nguyenpd-lts**
Hexabase CLI Enhancement to output Hexabase settings to local JSON file

https://github.com/b-eee/Hexabase/issues/163

### CODE REVIEW

**Comment by okamura-asnet** [comment]
Hi @Nguyenpd-lts .

Would you please use `this.log()` if possible? instead of `console.log()`.
FYR : https://oclif.io/docs/commands#thislogmessage-string

It seems to be deleted `hx projects:settings:download` command.
could you please enable `hx projects:settings:download` command, too?
`hx projects:settings:download` : downloads single(application or datasotre or action)
`hx projects:settings:download_all` : downloads all(application, datasotre and action)

**Comment by Nguyenpd-lts** [comment]
> 
I fixed this.log
In one file just have one command. so we can't have both commands in one file.

**Comment by okamura-asnet** [comment]
Hi @Nguyenpd-lts .
Thank you for your fix!
LGTM!

@iwask 
Please check.

**Review by iwask — APPROVED** [review]
cool. LGTM. thanks!  @Nguyenpd-lts @okamura-asnet 

```
$ hx pj:settings:getall
? Specify the output of the settingtestsettingsings
√ Specify the output of the setting file · testsettings
√ Select your project · 611be3b251eca76ebec45deb
completed save file: hexabase/testsettings/TestApp/app-settings.json
completed save file: hexabase/testsettings/TestApp/TODO-SAMPLE/datastore-settings.json
completed save file: hexabase/testsettings/TestApp/TODO-SAMPLE/action-settings.json
completed save file: hexabase/testsettings/TestApp/LineItems/datastore-settings.json
completed save file: hexabase/testsettings/TestApp/LineItems/action-settings.json
completed save file: hexabase/testsettings/TestApp/TestDB/datastore-settings.json
completed save file: hexabase/testsettings/TestApp/TestDB/action-settings.json
completed save file: hexabase/testsettings/TestApp/MasterDB1/datastore-settings.json
completed save file: hexabase/testsettings/TestApp/MasterDB1/action-settings.json
completed save file: hexabase/testsettings/TestApp/Tran01/datastore-settings.json
completed save file: hexabase/testsettings/TestApp/Tran01/action-settings.json
completed save file: hexabase/testsettings/TestApp/Db-RJfvpxTO/datastore-settings.json
completed save file: hexabase/testsettings/TestApp/Db-RJfvpxTO/action-settings.json
You can specify the output folder with the '--output' flag in the future
```

**Pull request merged**
