### PR TITLE
Feat1199396546824206: CLI actions & fields

### PR DESCRIPTION
**Pull request by alpenfritz**
## Issue

- CLI enhancements: actions & fields
- https://app.asana.com/0/inbox/1198845117023137/1199396546824206/1199400713490786

## Related Services

- linkermodels
- apicore
- linker-api
- web-ui
- hexabase-cli

## Implementation

- add `action` cmds: create, delete, get, show, update
- add `fields` cmds: create, delete, get, show, update
- add `statuses` cmd: get
- add `datastores` cmd: get
- add `projects` cmd: get & roles:get
- refactor to use `APIClient` and `SSEClient` classes
- modify `azure-pipeline` to skip already published packages
- add MIT LICENSE

## Future work

- none

### CODE REVIEW

**Comment by iwask** [comment]
@alpenfritz thank you for making the features! 
i tested in my local, and looks nice!  

i have some issues. let me know (about 1). 

1) about actions:get 
i could list up state-less actions(datastore actions). nice. but i can't get status-actions because can't find the method to get status_id.  
this is not in my requirements but i think users want to know status_id to get actions.   
to get it, should we need 'status:get' cmd??  or something else?  
if you have any point of view, let me know pls. 



2) [ THIS IS NOT RELATED This PR ! ]
I found an error on creating new project from template(project:create) OR restore template(project:restore)
i got error 
```
[ERROR] error newAction.CreateAction in restoreActions display_id already exits: MoveToAssigned
```
this means duplicate display_id in the same.  we have to fix this template in STG at the moment

**Comment by alpenfritz** [comment]
@iwask 
i will investigate about (1).
i will fix (2)`new project from template` bug in linkermodels.

**Comment by alpenfritz** [comment]
@iwask 
regarding (2): this comes from duplicated displaydID in the seed files: `MoveToAssigned`
https://github.com/b-eee/apicore/commit/0d6c7c95062a82e039ce9672464e988957e9fa7d#diff-b0eda40208eb37e9de192663e4b701fab04ef4be39ad7a223ef39c200bf9cb9bR22
&
https://github.com/b-eee/apicore/commit/0d6c7c95062a82e039ce9672464e988957e9fa7d#diff-b0eda40208eb37e9de192663e4b701fab04ef4be39ad7a223ef39c200bf9cb9bR478

**Comment by alpenfritz** [comment]
@iwask 
i will add `status:get` cmd and corresponding endpoint to linker-api using `get_status_and_order_settings` from apicorer

**Review by Hokutosei — APPROVED** [review]

**Pull request merged**
