### PR TITLE
Feat1199351279500061: cli for upload & download project templates

### PR DESCRIPTION
**Pull request by alpenfritz**
## Issue

- cli for upload & download project templates
- https://app.asana.com/0/1198845117032545/1199351279500075

## Related Services

- linker-api
- hexabase-cli

## Implementation

- refactored `BaseWithContext` class, so that we can include `--context` flag which overwrites `current-context`
- added `hx projects:backup [TEMPLATEID]` & `hx projects:restore FILE` commands
- added api calls to linker-api
- other refactoring

## Future work

- none

## Screenshots

image

`hx projects:backup`
image
image
image
image

`hx projects:restore`
image
image
image

### CODE REVIEW

**Review by Hokutosei — APPROVED** [review]
いいね

**Review by iwask — APPROVED** [review]
cool!

**Comment by iwask** [comment]
@alpenfritz I could download template in my local (windows).  👍 
but cant restore from windows cmd.exe...  😕 
something wrong??

2020-12-26_23h45_33

--
and cant select template in a GitBash 
 `select a template`  cant use down-arrow key..　
we should add NOTES for this restriction into a doc.

**Comment by alpenfritz** [comment]
@iwask `npm install` is needed for uploading files.
--
prompts in windows seem to be limited. someone with a windows machine needs to test & maybe develop with me.

**Comment by iwask** [comment]
@alpenfritz ok.   i will try npm install. 

lets discuss about members to develop the cli. w/  @Hokutosei or @marwenbhz 

@alpenfritz and you can bring windows machine.  there are two Razer high-spec machines available in our office.

**Comment by alpenfritz** [comment]
ok

**Comment by Hokutosei** [comment]
@iwask try using git-bash. cmd.exe has less support

**Comment by alpenfritz** [comment]
@iwask can i merge?? otherwise i will close the PR & refactor on this branch.

**Comment by alpenfritz** [comment]
@iwask can i merge & publish?

**Comment by iwask** [comment]
@alpenfritz yes, please! 
in my local, current workspace should be okay. but cant restore after npm install. 
i will test again after publish.

**Pull request merged**
